customCommands:
  - key: 'C'
    context: 'files'
    description: 'commit with convention'
    prompts:
      - type: 'menu'
        title: 'Select Commit Type'
        key: 'Type'
        options:
          - name: 'feat'
            description: 'A new feature'
            value: 'feat'
          - name: 'fix'
            description: 'A bug fix'
          - name: 'chore'
            description: 'Build process or auxiliary tool changes'
          - name: 'refactor'
            description: 'A code change that neither fixes a bug nor adds a feature'
          - name: 'style'
            description: 'Markup, white-space, formatting, missing semi-colons...'
          - name: 'docs'
            description: 'Documentation only changes'
          - name: 'perf'
            description: 'A code change that improves performance'
          - name: 'test'
            description: 'Adding missing tests or correcting existing tests'
          - name: 'build'
            description: 'Changes that affect the build system or external dependencies'
          - name: 'ci'
            description: 'Changes to our CI configuration files and scripts'
          - name: 'revert'
            description: 'Reverts a previous commit'
      - type: 'input'
        title: 'Enter Scope (optional, press Enter to skip)'
        key: 'Scope'
      - type: 'input'
        title: 'Enter Commit Message'
        key: 'Message'
    command: 'git commit -m "{{.Form.Type}}{{if .Form.Scope}}({{.Form.Scope}}){{end}}: {{.Form.Message}}"'
    loadingText: 'Committing...'